<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AudioApi" Version="1.0.6" />
    <PackageReference Include="DualSenseAPI" Version="1.0.2" />
    <PackageReference Include="Facepunch.Steamworks" Version="2.3.3" />
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.4" />
    <PackageReference Include="SteamKit2" Version="3.3.1" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
    <Folder Include="Assets/"/>
    <Resource Include="Assets/PichalLeafMask.png"/>
    <Resource Include="Assets/PichalLogoFull.png"/>
    <Resource Include="Assets/PichalLeaf.png"/>
    <Resource Include="Assets/Fox.png"/>
  </ItemGroup>

</Project>
